# Generated by Django 4.2 on 2023-05-16 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_task_points_teststudent_answerstudent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teststudent',
            old_name='task',
            new_name='test',
        ),
    ]
