# Generated by Django 4.2 on 2023-05-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_task_teststudent_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='teststudent',
            name='submitted_on_time',
            field=models.BooleanField(default=True),
        ),
    ]
