# Generated by Django 4.2 on 2023-05-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_teststudent_submitted_on_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
